list: $/frukt/kadr/models/family/columns.yaml
modelClass: Frukt\Kadr\Models\Family
title: Families
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'frukt/kadr/families/update/:id'
