list: $/frukt/kadr/models/reasdis/columns.yaml
modelClass: Frukt\Kadr\Models\Reasdis
title: Reasdises
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'frukt/kadr/reasdises/update/:id'
