list: $/frukt/kadr/models/sex/columns.yaml
modelClass: Frukt\Kadr\Models\Sex
title: Sexs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'frukt/kadr/sexs/update/:id'
