list: $/frukt/kadr/models/condition/columns.yaml
modelClass: Frukt\Kadr\Models\Condition
title: Conditions
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'frukt/kadr/conditions/update/:id'
